version: "3.8"
services:
  unifi-controller:
    image: lscr.io/linuxserver/unifi-controller:latest
    container_name: unifi-controller
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Adelaide
  #    - MEM_LIMIT=1024 #optional
  #    - MEM_STARTUP=1024 #optional
    volumes:
      -  /mnt/pve/docker-data-nfs/apps/unifi-controller/config2:/config
    ports:
      - target: 8443
        publihsed: 8443
        protocol: tcp
        mode: host
      - target: 3478
        publihsed: 3478
        protocol: udp
        mode: host
      - target: 10001
        publihsed: 10001
        protocol: udp
        mode: host
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
   #   - 1900:1900/udp #optional
   #   - 8843:8843 #optional
   #   - 8880:8880 #optional
   #   - 6789:6789 #optional
   #   - 5514:5514/udp #optional
    restart: unless-stopped
